FROM mysql:8.0
COPY . /docker-entrypoint-initdb.d/
# RUN -p 3306 -e MYSQL_ROOT_PASSWORD=123
# RUN mysql -p 3306 -e MYSQL_ROOT_PASSWORD=123 
# RUN -it exmgit-db-1 mysql -uroot -p123
# RUN mysql -p 123 mysql < chipization.sql
